Style Leaderboard
zainsadaqat/leaderboard pull request #8
Opened 2021-09-03 17:04 UTC by zainsadaqat

In this pull request, I implemented the following features:
- Use pure CSS
- Google Fonts
- Keep general layout of wireframe
- Improve look and feel of the project

![](https://media1.giphy.com/media/UtEUhkfriklonVdweC/giphy.gif)

2021-09-03 18:00 UTC, Dipeshtwis requested changes
Hi @zainsadaqat, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: README file looks professional.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

- [x] The link is broken in the readme file. Please fix that to make the README professional.

![Screenshot from 2021-09-03 23-25-45](https://user-images.githubusercontent.com/22434660/132047896-68966861-6144-4d21-8d60-d2869c32eacb.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- You can also include the instruction like `npm i` and `npm start` to install and run the project.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-03 18:00 UTC, Dipeshtwis commented on src/index.html
> +        </ul>
- [x] I would recommend giving proper margin between `recent score` and `add your score` section to make the UI nice. Please work on that.

### Your Design

![Screenshot from 2021-09-03 23-03-42](https://user-images.githubusercontent.com/22434660/132045476-72150c99-fd50-4bcd-8a92-4998b83ef61e.png)


### Original Design

![Screenshot from 2021-09-01 05-05-45](https://user-images.githubusercontent.com/22434660/132045538-eb4258ba-7dc6-42f0-bcb6-b74806cbd0e5.png)

2021-09-03 21:36 UTC, sinansevgi approved these changes
# Approved :heavy_check_mark: 

Hi  @zainsadaqat.

Great design :clap:
Your project is complete!  
Congratulations! 🎉

You can merge this pull request and continue with your journey :wave: 


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-03 22:16 UTC, merged

2021-09-03 22:17 UTC, zainsadaqat commented on src/index.html
> +        </ul>
## Project has perfect padding and margins.

![Screenshot from 2021-09-04 02-03-15](https://user-images.githubusercontent.com/83048208/132065134-6c0ebeb9-aab4-4145-b256-029e0cc32123.png)

2022-01-22 13:08 UTC, zainsadaqat commented
# Thanks, @sinansevgi for approving this pull request!

<img src="https://media1.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif"/>